---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik-production
resources:
  - namespace.yaml
  - ../base

patchesStrategicMerge:
  - traefik-patch.yaml
  - ingressroute-patch.yaml