---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: whoami-production
resources:
  - namespace.yaml
  - ../base

patchesStrategicMerge:
  - whoami-patch.yaml
  - ingressroute-patch.yaml